// templates/vue-chat-tsx-vike/pages/index/ChatPanel.tsx
import { defineComponent } from 'vue'
import { Chatbot } from '@tdesign-vue-next/chat'
import type { AIMessageContent, ChatServiceConfig, SSEChunkData } from '@tdesign-vue-next/chat'

const chatServiceConfig: ChatServiceConfig = {
  endpoint: 'https://1257786608-9i9j1kpa67.ap-guangzhou.tencentscf.com/sse/normal',
  stream: true,
  onMessage: (chunk: SSEChunkData): AIMessageContent => {
    const data = chunk.data as { msg?: string } | undefined

    return {
      type: 'markdown',
      data: data?.msg ?? '',
    }
  },
}

export default defineComponent(() => {
  return () => (
    <div class="chatbot-host">
      <Chatbot chatServiceConfig={chatServiceConfig} />
    </div>
  )
})

// templates/react-chat-vike/pages/index/ChatPanel.tsx
import { ChatBot } from '@tdesign-react/chat'
import type { AIMessageContent, ChatServiceConfig, SSEChunkData } from '@tdesign-react/chat'
import '@tdesign-react/chat/es/style/index.js'

const chatServiceConfig: ChatServiceConfig = {
  endpoint: 'https://1257786608-9i9j1kpa67.ap-guangzhou.tencentscf.com/sse/normal',
  stream: true,
  onMessage: (chunk: SSEChunkData): AIMessageContent => {
    const data = chunk.data as { msg?: string } | undefined

    return {
      type: 'markdown',
      data: data?.msg ?? '',
    }
  },
}

export default function ChatPanel() {
  return (
    <div className="chatbot-host">
      <ChatBot chatServiceConfig={chatServiceConfig} />
    </div>
  )
}
