// templates/mobile-react-vite/src/pages/Dependencies.tsx
import { useEffect, useState } from 'react'
import {
  AppIcon,
  ChevronLeftIcon,
  CodeIcon,
  ComponentGridIcon,
  MoonIcon,
  SunnyIcon,
} from 'tdesign-icons-react'
import { Button, Cell, CellGroup, Grid, GridItem, Navbar, Typography } from 'tdesign-mobile-react'
import packageJson from '../../package.json'
import logoDark from '../assets/TDesign-logo_dark.png'
import logoLight from '../assets/TDesign-logo_light.png'
import './Dependencies.css'

const STORAGE_KEY = 'tdesign-starter-theme'
const runtimeDependencies = Object.entries(packageJson.dependencies ?? {})
const developmentDependencies = Object.entries(packageJson.devDependencies ?? {})
const totalDependencies = runtimeDependencies.length + developmentDependencies.length

export default function DependenciesPage() {
  const [isDark, setIsDark] = useState(false)
  const themeLabel = isDark ? 'Switch to light theme' : 'Switch to dark theme'
  function applyTheme(dark: boolean) {
    setIsDark(dark)
    document.documentElement.setAttribute('theme-mode', dark ? 'dark' : 'light')
  }
  function toggleTheme() {
    const nextDark = !isDark
    applyTheme(nextDark)
    localStorage.setItem(STORAGE_KEY, nextDark ? 'dark' : 'light')
  }
  useEffect(() => {
    const savedTheme = localStorage.getItem(STORAGE_KEY)
    applyTheme(
      savedTheme ? savedTheme === 'dark' : matchMedia('(prefers-color-scheme: dark)').matches,
    )
  }, [])
  const dependencySection = (title: string, dependencies: [string, string][]) => (
    <section className="dependency-section" aria-label={title}>
      <div className="dependency-heading">
        <Typography.Title level="h2">{title}</Typography.Title>
        <Typography.Text theme="secondary">{dependencies.length} packages</Typography.Text>
      </div>
      <CellGroup theme="card">
        {dependencies.map(([name, version]) => (
          <Cell
            className="dependency-cell"
            key={name}
            title={<Typography.Text strong>{name}</Typography.Text>}
            note={
              <span className="dependency-version">
                <Typography.Text code copyable={{ text: version }}>
                  {version}
                </Typography.Text>
              </span>
            }
          />
        ))}
      </CellGroup>
    </section>
  )
  return (
    <main className="page-shell dependencies-page">
      <Navbar
        className="brand-navbar"
        fixed={false}
        left={
          <div className="brand-lockup">
            <button
              className="back-button"
              type="button"
              aria-label="Back to home"
              title="Back to home"
              onClick={() => window.location.assign('/')}
            >
              <ChevronLeftIcon size="22px" />
            </button>
            <img className="brand-logo" src={isDark ? logoDark : logoLight} alt="TDesign" />
          </div>
        }
        right={
          <button
            className="theme-button"
            type="button"
            aria-label={themeLabel}
            title={themeLabel}
            onClick={(event) => {
              event.stopPropagation()
              toggleTheme()
            }}
          >
            {isDark ? <SunnyIcon size="20px" /> : <MoonIcon size="20px" />}
          </button>
        }
      />
      <section className="dependencies-hero">
        <div className="dependencies-width">
          <Typography.Text className="dependencies-kicker" theme="primary">
            Project manifest
          </Typography.Text>
          <Typography.Title level="h1">Dependencies</Typography.Title>
          <Typography.Paragraph className="dependencies-copy">
            Packages available in this starter, with the exact version ranges from package.json.
          </Typography.Paragraph>
          <Grid className="dependencies-summary" column={3} border theme="card">
            <GridItem
              image={<AppIcon size="24px" />}
              text={<Typography.Title level="h3">{runtimeDependencies.length}</Typography.Title>}
              description={<Typography.Text theme="secondary">Runtime</Typography.Text>}
            />
            <GridItem
              image={<CodeIcon size="24px" />}
              text={
                <Typography.Title level="h3">{developmentDependencies.length}</Typography.Title>
              }
              description={<Typography.Text theme="secondary">Development</Typography.Text>}
            />
            <GridItem
              image={<ComponentGridIcon size="24px" />}
              text={<Typography.Title level="h3">{totalDependencies}</Typography.Title>}
              description={<Typography.Text theme="secondary">Total</Typography.Text>}
            />
          </Grid>
        </div>
      </section>
      <div className="dependencies-width dependencies-content">
        {dependencySection('Runtime dependencies', runtimeDependencies)}
        {dependencySection('Development dependencies', developmentDependencies)}
        <Button
          className="dependencies-home"
          variant="outline"
          size="large"
          block
          onClick={() => window.location.assign('/')}
        >
          Back to home
        </Button>
      </div>
    </main>
  )
}

// templates/mobile-vue-rsbuild/src/pages/Dependencies.vue
<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import {
  AppIcon,
  ChevronLeftIcon,
  CodeIcon,
  ComponentGridIcon,
  MoonIcon,
  SunnyIcon,
} from 'tdesign-icons-vue-next'
import packageJson from '../../package.json'
import logoDark from '../assets/TDesign-logo_dark.png'
import logoLight from '../assets/TDesign-logo_light.png'
import './Dependencies.css'

const STORAGE_KEY = 'tdesign-starter-theme'
const isDark = ref(false)
const themeLabel = computed(() => (isDark.value ? 'Switch to light theme' : 'Switch to dark theme'))
const runtimeDependencies = Object.entries(packageJson.dependencies ?? {})
const developmentDependencies = Object.entries(packageJson.devDependencies ?? {})
const totalDependencies = runtimeDependencies.length + developmentDependencies.length
function applyTheme(dark: boolean) {
  isDark.value = dark
  document.documentElement.setAttribute('theme-mode', dark ? 'dark' : 'light')
}
function toggleTheme() {
  const nextDark = !isDark.value
  applyTheme(nextDark)
  localStorage.setItem(STORAGE_KEY, nextDark ? 'dark' : 'light')
}
function goHome() {
  window.location.assign('/')
}
onMounted(() => {
  const savedTheme = localStorage.getItem(STORAGE_KEY)
  applyTheme(
    savedTheme ? savedTheme === 'dark' : matchMedia('(prefers-color-scheme: dark)').matches,
  )
})
</script>

<template>
  <main class="page-shell dependencies-page">
    <t-navbar class="brand-navbar" :fixed="false">
      <template #left>
        <div class="brand-lockup">
          <button
            class="back-button"
            type="button"
            aria-label="Back to home"
            title="Back to home"
            @click="goHome"
          >
            <ChevronLeftIcon size="22px" />
          </button>
          <img class="brand-logo" :src="isDark ? logoDark : logoLight" alt="TDesign" />
        </div>
      </template>
      <template #right>
        <button
          class="theme-button"
          type="button"
          :aria-label="themeLabel"
          :title="themeLabel"
          @click.stop="toggleTheme"
        >
          <SunnyIcon v-if="isDark" size="20px" />
          <MoonIcon v-else size="20px" />
        </button>
      </template>
    </t-navbar>
    <section class="dependencies-hero">
      <div class="dependencies-width">
        <t-typography-text class="dependencies-kicker" theme="primary">
          Project manifest
        </t-typography-text>
        <t-typography-title level="h1">Dependencies</t-typography-title>
        <div class="dependencies-copy">
          <t-typography-paragraph>
            Packages available in this starter, with the exact version ranges from package.json.
          </t-typography-paragraph>
        </div>
        <t-grid class="dependencies-summary" :column="3" border theme="card">
          <t-grid-item>
            <template #image><AppIcon size="24px" /></template>
            <template #text>
              <t-typography-title level="h3">{{ runtimeDependencies.length }}</t-typography-title>
            </template>
            <template #description>
              <t-typography-text theme="secondary">Runtime</t-typography-text>
            </template>
          </t-grid-item>
          <t-grid-item>
            <template #image><CodeIcon size="24px" /></template>
            <template #text>
              <t-typography-title level="h3">
                {{ developmentDependencies.length }}
              </t-typography-title>
            </template>
            <template #description>
              <t-typography-text theme="secondary">Development</t-typography-text>
            </template>
          </t-grid-item>
          <t-grid-item>
            <template #image><ComponentGridIcon size="24px" /></template>
            <template #text>
              <t-typography-title level="h3">{{ totalDependencies }}</t-typography-title>
            </template>
            <template #description>
              <t-typography-text theme="secondary">Total</t-typography-text>
            </template>
          </t-grid-item>
        </t-grid>
      </div>
    </section>
    <div class="dependencies-width dependencies-content">
      <section class="dependency-section" aria-label="Runtime dependencies">
        <div class="dependency-heading">
          <t-typography-title level="h2">Runtime dependencies</t-typography-title>
          <span class="dependency-count">
            <t-typography-text theme="secondary">
              {{ runtimeDependencies.length }} packages
            </t-typography-text>
          </span>
        </div>
        <t-cell-group theme="card">
          <t-cell
            v-for="[name, version] in runtimeDependencies"
            :key="name"
            class="dependency-cell"
          >
            <template #title>
              <t-typography-text strong>{{ name }}</t-typography-text>
            </template>
            <template #note>
              <span class="dependency-version">
                <t-typography-text code :copyable="{ text: version }">
                  {{ version }}
                </t-typography-text>
              </span>
            </template>
          </t-cell>
        </t-cell-group>
      </section>
      <section class="dependency-section" aria-label="Development dependencies">
        <div class="dependency-heading">
          <t-typography-title level="h2">Development dependencies</t-typography-title>
          <span class="dependency-count">
            <t-typography-text theme="secondary">
              {{ developmentDependencies.length }} packages
            </t-typography-text>
          </span>
        </div>
        <t-cell-group theme="card">
          <t-cell
            v-for="[name, version] in developmentDependencies"
            :key="name"
            class="dependency-cell"
          >
            <template #title>
              <t-typography-text strong>{{ name }}</t-typography-text>
            </template>
            <template #note>
              <span class="dependency-version">
                <t-typography-text code :copyable="{ text: version }">
                  {{ version }}
                </t-typography-text>
              </span>
            </template>
          </t-cell>
        </t-cell-group>
      </section>
      <t-button class="dependencies-home" variant="outline" size="large" block @click="goHome">
        Back to home
      </t-button>
    </div>
  </main>
</template>
