// templates/react-rspack/src/App.tsx
import { Button, Card, Space, Tag } from 'tdesign-react'

const highlights = [
  'React + TypeScript',
  'Rspack dev/build pipeline',
  'TDesign desktop components',
]

export default function App() {
  return (
    <main className="page-shell">
      <section className="hero-grid">
        <Card className="hero-card" bordered={false}>
          <Space direction="vertical" size={16}>
            <Tag theme="primary" variant="light-outline">
              __TEMPLATENAME__
            </Tag>
            <div>
              <h1>Create TDesign</h1>
              <p>
                Your __PROJECTNAME__ project is ready. Start building with React,
                TypeScript, and TDesign.
              </p>
            </div>
            <Space>
              <Button theme="primary">Open Docs</Button>
              <Button variant="outline">Start Editing</Button>
            </Space>
          </Space>
        </Card>

        <Card title="What is included" className="panel-card">
          <Space direction="vertical" size={12}>
            {highlights.map((item) => (
              <div key={item} className="feature-row">
                <Tag theme="success" variant="light-outline">
                  Ready
                </Tag>
                <span>{item}</span>
              </div>
            ))}
          </Space>
        </Card>
      </section>
    </main>
  )
}

// templates/vue-tsx-rspack-on-demand/src/App.tsx
import { defineComponent } from 'vue'
const highlights = [
  'Vue 3 + TSX + TypeScript',
  'Rspack dev/build pipeline',
  'TDesign desktop components',
]

export default defineComponent(() => {
  return () => (
    <main class="page-shell">
      <section class="hero-grid">
        <TCard class="hero-card" bordered={false}>
          <TSpace direction="vertical" size="16px">
            <TTag theme="primary" variant="light">
              __TEMPLATENAME__
            </TTag>
            <div>
              <h1>Create TDesign</h1>
              <p>
                Your __PROJECTNAME__ project is ready. Start building with Vue,
                TSX, TypeScript, and TDesign.
              </p>
            </div>
            <TSpace>
              <TButton theme="primary">Open Docs</TButton>
              <TButton variant="outline">Start Editing</TButton>
            </TSpace>
          </TSpace>
        </TCard>

        <TCard title="What is included" class="panel-card">
          <TSpace direction="vertical" size="12px">
            {highlights.map((item) => (
              <div key={item} class="feature-row">
                <TTag theme="success" variant="light">
                  Ready
                </TTag>
                <span>{item}</span>
              </div>
            ))}
          </TSpace>
        </TCard>
      </section>
    </main>
  )
})
