// templates/vue-tsx-rsbuild/src/pages/Demo.tsx
import { defineComponent, ref } from 'vue'
import {
  Avatar as TAvatar,
  Badge as TBadge,
  Button as TButton,
  Card as TCard,
  Space as TSpace,
  Tag as TTag,
} from 'tdesign-vue-next'

export default defineComponent({
  name: 'Demo',
  setup() {
    const count = ref(0)
    const decrease = () => {
      count.value -= 1
    }
    const increase = () => {
      count.value += 1
    }

    return () => (
      <TCard class="demo-panel" bordered>
        {{
          header: () => (
            <div class="demo-head">
              <div class="demo-title">
                <TBadge dot color="var(--starter-green)" />
                示例
              </div>
              <span class="demo-subtitle">交互示例</span>
            </div>
          ),
          default: () => (
            <div class="demo-stage">
              <div class="demo-card">
                <TAvatar class="demo-mark" size="54px" shape="round" style={{ background: 'var(--starter-blue)', color: 'var(--td-text-color-anti)', fontWeight: 800 }}>T</TAvatar>
                <h2>Hello, TDesign</h2>
                <p>点击按钮，体验这个模板中的基础交互。</p>
                <TSpace size={12} align="center">
                  <TButton
                    class="demo-button"
                    shape="square"
                    theme="primary"
                    onClick={decrease}
                    aria-label="减少"
                  >
                    {{
                      icon: () => '−',
                    }}
                  </TButton>
                  <TTag class="count" size="large" theme="primary" variant="light">
                    {count.value}
                  </TTag>
                  <TButton
                    class="demo-button"
                    shape="square"
                    theme="primary"
                    onClick={increase}
                    aria-label="增加"
                  >
                    {{
                      icon: () => '+',
                    }}
                  </TButton>
                </TSpace>
                <div class="hint">编辑首页文件并保存，查看热更新效果</div>
              </div>
            </div>
          ),
        }}
      </TCard>
    )
  },
})

// templates/react-rsbuild/src/pages/Demo.tsx
import { useState } from 'react'
import { Avatar, Badge, Button, Card, Space, Tag } from 'tdesign-react'

export default function Demo() {
  const [count, setCount] = useState(0)

  return (
    <Card
      className="demo-panel"
      bordered
      header={
        <div className="demo-head">
          <div className="demo-title">
            <Badge dot color="var(--starter-green)" />
            示例
          </div>
          <span className="demo-subtitle">交互示例</span>
        </div>
      }
    >
      <div className="demo-stage">
        <div className="demo-card">
          <Avatar className="demo-mark" size="54px" shape="round" style={{ background: 'var(--starter-blue)', color: 'var(--td-text-color-anti)', fontWeight: 800 }}>T</Avatar>
          <h2>Hello, TDesign</h2>
          <p>点击按钮，体验这个模板中的基础交互。</p>
          <Space size={12} align="center">
            <Button
              className="demo-button"
              shape="square"
              theme="primary"
              onClick={() => setCount((c) => c - 1)}
              aria-label="减少"
            >
              −
            </Button>
            <Tag className="count" size="large" theme="primary" variant="light">
              {count}
            </Tag>
            <Button
              className="demo-button"
              shape="square"
              theme="primary"
              onClick={() => setCount((c) => c + 1)}
              aria-label="增加"
            >
              +
            </Button>
          </Space>
          <div className="hint">编辑首页文件并保存，查看热更新效果</div>
        </div>
      </div>
    </Card>
  )
}
