// templates/vue-vite/src/pages/Dependencies.vue
<script setup lang="ts">
import { computed, ref } from 'vue'
import { ArrowLeftIcon, ComponentGridIcon, MoonIcon, SunnyIcon } from 'tdesign-icons-vue-next'
import packageJson from '../../package.json'
import logoDark from '../assets/TDesign-logo_dark.png'
import logoLight from '../assets/TDesign-logo_light.png'

type Theme = 'light' | 'dark'

const themeKey = 'tdesign-starter-theme'
const getInitialTheme = (): Theme => {
  if (typeof window === 'undefined') return 'light'
  const savedTheme = window.localStorage.getItem(themeKey)
  if (savedTheme === 'light' || savedTheme === 'dark') return savedTheme
  return window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light'
}

const theme = ref<Theme>(getInitialTheme())
const isDark = computed(() => theme.value === 'dark')
const logo = computed(() => (isDark.value ? logoDark : logoLight))
const runtimeDependencies = Object.entries(packageJson.dependencies ?? {})
const developmentDependencies = Object.entries(packageJson.devDependencies ?? {})
const dependencyGroups = [
  { title: 'Runtime dependencies', items: runtimeDependencies },
  { title: 'Development dependencies', items: developmentDependencies },
]
const summary = [
  {
    title: 'Total',
    value: runtimeDependencies.length + developmentDependencies.length,
  },
  { title: 'Runtime', value: runtimeDependencies.length },
  { title: 'Development', value: developmentDependencies.length },
]

const applyTheme = (nextTheme: Theme) => {
  if (typeof document === 'undefined') return
  if (nextTheme === 'dark') document.documentElement.setAttribute('theme-mode', 'dark')
  else document.documentElement.removeAttribute('theme-mode')
}

applyTheme(theme.value)

const toggleTheme = () => {
  theme.value = isDark.value ? 'light' : 'dark'
  window.localStorage.setItem(themeKey, theme.value)
  applyTheme(theme.value)
}
</script>

<template>
  <t-layout class="dependencies-page">
    <t-header class="dependencies-topbar">
      <t-row class="dependencies-topbar-inner" align="middle" justify="space-between">
        <a href="./" aria-label="Back to home">
          <img :src="logo" alt="TDesign" />
        </a>
        <t-space class="dependencies-actions" :size="4">
          <t-button tag="a" href="./" variant="text">
            <ArrowLeftIcon />
            Home
          </t-button>
          <t-tooltip :content="isDark ? 'Switch to light theme' : 'Switch to dark theme'">
            <t-button
              shape="circle"
              variant="text"
              :aria-label="isDark ? 'Switch to light theme' : 'Switch to dark theme'"
              @click="toggleTheme"
            >
              <SunnyIcon v-if="isDark" />
              <MoonIcon v-else />
            </t-button>
          </t-tooltip>
        </t-space>
      </t-row>
    </t-header>

    <t-content class="dependencies-workspace">
      <section aria-labelledby="dependencies-title">
        <t-row class="dependencies-intro" align="bottom" justify="space-between">
          <t-space direction="vertical" size="small">
            <t-tag theme="primary" variant="light">Package manifest</t-tag>
            <div id="dependencies-title">
              <t-typography-title level="h1">Dependencies</t-typography-title>
            </div>
            <t-typography-text theme="secondary">
              Packages declared by
              <t-typography-text code>{{ packageJson.name }}</t-typography-text>
              , grouped by how they are used.
            </t-typography-text>
          </t-space>
          <span class="dependencies-title-icon"><ComponentGridIcon /></span>
        </t-row>
      </section>

      <section class="dependencies-summary" aria-label="Dependency summary">
        <t-row :gutter="[16, 16]">
          <t-col v-for="item in summary" :key="item.title" :xs="12" :sm="4">
            <t-card :bordered="true">
              <t-statistic :title="item.title" :value="item.value" />
            </t-card>
          </t-col>
        </t-row>
      </section>

      <section aria-label="Dependency lists">
        <t-row align="top" :gutter="[16, 16]">
          <t-col v-for="group in dependencyGroups" :key="group.title" :xs="12" :sm="6">
            <t-card class="dependencies-card" :bordered="true" header-bordered>
              <template #title>
                <t-typography-text strong>{{ group.title }}</t-typography-text>
              </template>
              <template #actions>
                <t-tag variant="light">{{ group.items.length }} packages</t-tag>
              </template>
              <t-list split>
                <t-list-item v-for="[name, version] in group.items" :key="name">
                  <t-typography-text class="dependency-name" strong>
                    {{ name }}
                  </t-typography-text>
                  <template #action>
                    <t-typography-text code :copyable="{ text: version }">
                      {{ version }}
                    </t-typography-text>
                  </template>
                </t-list-item>
              </t-list>
            </t-card>
          </t-col>
        </t-row>
      </section>
    </t-content>
  </t-layout>
</template>

<style scoped>


:global(*) {
  box-sizing: border-box;
}
:global(body) {
  margin: 0;
  min-width: 320px;
  min-height: 100vh;
  background: var(--td-bg-color-page);
}
.dependencies-page {
  min-height: 100vh;
  color: var(--td-text-color-primary);
  background: var(--td-bg-color-page);
}
.dependencies-topbar {
  border-bottom: 1px solid var(--td-component-border);
  background: var(--td-bg-color-container);
}
.dependencies-topbar-inner {
  width: 100%;
  max-width: 1232px;
  height: 64px;
  margin: 0 auto;
  padding: 0 24px;
}
.dependencies-topbar-inner img {
  display: block;
  width: 132px;
  height: auto;
}
.dependencies-actions :deep(.t-button) {
  color: var(--td-text-color-secondary);
}
.dependencies-workspace {
  width: 100%;
  max-width: 1232px;
  margin: 0 auto;
  padding: 44px 24px 64px;
}
.dependencies-intro {
  margin-bottom: 24px;
}
.dependencies-title-icon {
  display: inline-flex;
  width: 48px;
  height: 48px;
  flex: 0 0 auto;
  border-radius: 8px;
  align-items: center;
  justify-content: center;
  color: var(--td-brand-color);
  background: var(--td-brand-color-light);
  font-size: 25px;
}
.dependencies-summary {
  margin-bottom: 16px;
}
.dependencies-card {
  height: 100%;
}
.dependencies-card :deep(.t-card__body) {
  padding: 0;
}
.dependency-name {
  min-width: 0;
  overflow-wrap: anywhere;
}
@media (max-width: 760px) {
  .dependencies-topbar-inner {
    padding: 0 16px;
  }
  .dependencies-topbar-inner img {
    width: 116px;
  }
  .dependencies-workspace {
    padding: 32px 16px 48px;
  }
}
@media (max-width: 420px) {
  .dependencies-title-icon {
    display: none;
  }
}
</style>

// templates/react-rsbuild/src/pages/Dependencies.tsx
import { useEffect, useState } from 'react'
import {
  ArrowLeftIcon,
  ComponentGridIcon,
  MoonIcon,
  SunnyIcon,
} from 'tdesign-icons-react'
import {
  Button,
  Card,
  Col,
  Layout,
  List,
  Row,
  Space,
  Statistic,
  Tag,
  Tooltip,
  Typography,
} from 'tdesign-react'
import packageJson from '../../package.json'
import logoDark from '../assets/TDesign-logo_dark.png'
import logoLight from '../assets/TDesign-logo_light.png'
import './Dependencies.css'

type Theme = 'light' | 'dark'

const themeKey = 'tdesign-starter-theme'
const runtimeDependencies = Object.entries(packageJson.dependencies ?? {})
const developmentDependencies = Object.entries(
  packageJson.devDependencies ?? {},
)
const dependencyGroups = [
  { title: 'Runtime dependencies', items: runtimeDependencies },
  { title: 'Development dependencies', items: developmentDependencies },
]
const summary = [
  {
    title: 'Total',
    value: runtimeDependencies.length + developmentDependencies.length,
  },
  { title: 'Runtime', value: runtimeDependencies.length },
  { title: 'Development', value: developmentDependencies.length },
]

const getInitialTheme = (): Theme => {
  if (typeof window === 'undefined') return 'light'
  const savedTheme = window.localStorage.getItem(themeKey)
  if (savedTheme === 'light' || savedTheme === 'dark') return savedTheme
  return window.matchMedia('(prefers-color-scheme: dark)').matches
    ? 'dark'
    : 'light'
}

const applyTheme = (theme: Theme) => {
  if (typeof document === 'undefined') return
  if (theme === 'dark')
    document.documentElement.setAttribute('theme-mode', 'dark')
  else document.documentElement.removeAttribute('theme-mode')
}

export default function DependenciesPage() {
  const [theme, setTheme] = useState<Theme>(getInitialTheme)
  const isDark = theme === 'dark'

  useEffect(() => applyTheme(theme), [theme])

  const toggleTheme = () => {
    const nextTheme = isDark ? 'light' : 'dark'
    setTheme(nextTheme)
    window.localStorage.setItem(themeKey, nextTheme)
  }

  return (
    <Layout className="dependencies-page">
      <Layout.Header className="topbar">
        <Row className="topbar-inner" align="middle" justify="space-between">
          <a href="./" className="dependencies-brand" aria-label="Back to home">
            <img
              className="brand-logo"
              src={isDark ? logoDark : logoLight}
              alt="TDesign"
            />
          </a>
          <Space className="topbar-actions" size={4}>
            <Button tag="a" href="./" variant="text">
              <ArrowLeftIcon />
              Home
            </Button>
            <Tooltip
              content={
                isDark ? 'Switch to light theme' : 'Switch to dark theme'
              }
            >
              <Button
                shape="circle"
                variant="text"
                aria-label={
                  isDark ? 'Switch to light theme' : 'Switch to dark theme'
                }
                onClick={toggleTheme}
              >
                {isDark ? <SunnyIcon /> : <MoonIcon />}
              </Button>
            </Tooltip>
          </Space>
        </Row>
      </Layout.Header>

      <Layout.Content className="dependencies-workspace">
        <section aria-labelledby="dependencies-title">
          <Row className="dependencies-intro" align="bottom" justify="space-between">
            <Space direction="vertical" size="small">
              <Tag theme="primary" variant="light">
                Package manifest
              </Tag>
              <div id="dependencies-title">
                <Typography.Title level="h1">Dependencies</Typography.Title>
              </div>
              <Typography.Text theme="secondary">
                Packages declared by{' '}
                <Typography.Text code>{packageJson.name}</Typography.Text>, grouped
                by how they are used.
              </Typography.Text>
            </Space>
            <span className="dependencies-title-icon">
              <ComponentGridIcon />
            </span>
          </Row>
        </section>

        <section className="dependencies-summary" aria-label="Dependency summary">
          <Row gutter={[16, 16]}>
            {summary.map((item) => (
              <Col key={item.title} xs={12} sm={4}>
                <Card bordered>
                  <Statistic title={item.title} value={item.value} />
                </Card>
              </Col>
            ))}
          </Row>
        </section>

        <section aria-label="Dependency lists">
          <Row align="top" gutter={[16, 16]}>
            {dependencyGroups.map((group) => (
              <Col key={group.title} xs={12} sm={6}>
                <Card
                  className="dependencies-card"
                  title={<Typography.Text strong>{group.title}</Typography.Text>}
                  actions={<Tag variant="light">{group.items.length} packages</Tag>}
                  bordered
                  headerBordered
                >
                  <List split>
                    {group.items.map(([name, version]) => (
                      <List.ListItem
                        key={name}
                        action={
                          <Typography.Text code copyable={{ text: version }}>
                            {version}
                          </Typography.Text>
                        }
                      >
                        <Typography.Text className="dependency-name" strong>
                          {name}
                        </Typography.Text>
                      </List.ListItem>
                    ))}
                  </List>
                </Card>
              </Col>
            ))}
          </Row>
        </section>
      </Layout.Content>
    </Layout>
  )
}
