// templates/react-vite/src/App.tsx
import { Button, Card, Space } from 'tdesign-react'
import { AppIcon } from 'tdesign-icons-react'

const sections = [
  {
    title: 'Starter stack',
    description: 'Built with React, TypeScript, and TDesign desktop components.',
  },
  {
    title: 'Build workflow',
    description: 'Use Vite for instant local startup and production builds.',
  },
  {
    title: 'Next step',
    description: 'Open src/App.tsx and start shaping __PROJECTNAME__.',
  },
]

export default function App() {
  return (
    <main className="page-shell">
      <section className="hero-grid">
        <Card className="hero-card" bordered={false}>
          <Space direction="vertical" size={20}>
            <p className="eyebrow">
              <AppIcon style={{ marginRight: '6px', verticalAlign: 'middle' }} />
              __TEMPLATENAME__
            </p>
            <div className="hero-copy">
              <h1 className="hero-title">Create TDesign</h1>
              <p className="hero-intro">
                Your __PROJECTNAME__ project is ready. Start building with React,
                TypeScript, and TDesign.
              </p>
            </div>
            <div className="action-row">
              <Button theme="primary">Run pnpm dev</Button>
              <Button variant="outline">Open src/App.tsx</Button>
            </div>
          </Space>
        </Card>

        <Card className="panel-card">
          <div className="section-block">
            <p className="section-heading">Getting started</p>
            <div className="section-list">
              {sections.map((item) => (
                <div key={item.title} className="section-row">
                  <span className="section-row-title">{item.title}</span>
                  <p className="section-row-description">{item.description}</p>
                </div>
              ))}
            </div>
          </div>
        </Card>
      </section>
    </main>
  )
}

// templates/vue-tsx-vite-plus/src/App.tsx
import { defineComponent } from 'vue'
import { AppIcon } from 'tdesign-icons-vue-next'
import {
  Button as TButton,
  Card as TCard,
  Space as TSpace,
} from 'tdesign-vue-next'

const sections = [
  {
    title: 'Starter stack',
    description: 'Built with Vue 3, TSX, TypeScript, and TDesign desktop components.',
  },
  {
    title: 'Build workflow',
    description: 'Use Vite for instant local startup and production builds.',
  },
  {
    title: 'Next step',
    description: 'Open src/App.tsx and start shaping __PROJECTNAME__.',
  },
]

export default defineComponent(() => {
  return () => (
    <main class="page-shell">
      <section class="hero-grid">
        <TCard class="hero-card" bordered={false}>
          <TSpace direction="vertical" size="20px">
            <p class="eyebrow">
              <AppIcon style={{ marginRight: '6px', verticalAlign: 'middle' }} />
              __TEMPLATENAME__
            </p>
            <div class="hero-copy">
              <h1 class="hero-title">Create TDesign</h1>
              <p class="hero-intro">
                Your __PROJECTNAME__ project is ready. Start building with Vue,
                TSX, TypeScript, and TDesign.
              </p>
            </div>
            <div class="action-row">
              <TButton theme="primary">Run pnpm dev</TButton>
              <TButton variant="outline">Open src/App.tsx</TButton>
            </div>
          </TSpace>
        </TCard>

        <TCard class="panel-card">
          <div class="section-block">
            <p class="section-heading">Getting started</p>
            <div class="section-list">
              {sections.map((item) => (
                <div key={item.title} class="section-row">
                  <span class="section-row-title">{item.title}</span>
                  <p class="section-row-description">{item.description}</p>
                </div>
              ))}
            </div>
          </div>
        </TCard>
      </section>
    </main>
  )
})
