// templates/react-vike/pages/index/Demo.tsx
import { useState } from 'react'
import { Avatar, Badge, Button, Card, Space, Typography } from 'tdesign-react'

export default function Demo() {
  const [count, setCount] = useState(0)
  const decrease = () => {
    setCount((c) => c - 1)
  }
  const increase = () => {
    setCount((c) => c + 1)
  }

  return (
    <Card
      className="demo-panel"
      bordered
      header={
        <div className="demo-head">
          <div className="demo-title">
            <Badge dot color="var(--td-success-color)" />
            示例
          </div>
          <span className="demo-subtitle">交互示例</span>
        </div>
      }
    >
      <div className="demo-stage">
        <div className="demo-card">
          <Avatar
            className="demo-mark"
            size="54px"
            shape="round"
            style={{
              background: 'var(--td-brand-color)',
              color: 'var(--td-text-color-anti)',
              fontWeight: 800,
            }}
          >
            T
          </Avatar>
          <Typography.Title className="demo-card-title" level="h3">
            Hello, TDesign
          </Typography.Title>
          <Typography.Paragraph className="demo-card-copy" theme="secondary">
            点击按钮，体验这个模板中的基础交互。
          </Typography.Paragraph>
          <Space size={12} align="center">
            <Button
              theme="primary"
              size="large"
              shape="square"
              aria-label="减少"
              onClick={decrease}
            >
              −
            </Button>
            <Button variant="outline" size="large" disabled>
              {count}
            </Button>
            <Button
              theme="primary"
              size="large"
              shape="square"
              aria-label="增加"
              onClick={increase}
            >
              +
            </Button>
          </Space>
          <div className="hint">编辑首页文件并保存，查看热更新效果</div>
        </div>
      </div>
    </Card>
  )
}

// templates/vue-vike-on-demand/pages/index/Demo.vue
<script setup lang="ts">
import { ref } from 'vue'

const count = ref(0)
const decrease = () => {
  count.value -= 1
}
const increase = () => {
  count.value += 1
}
</script>

<template>
  <t-card class="demo-panel" :bordered="true">
    <template #header>
      <div class="demo-head">
        <div class="demo-title">
          <t-badge dot color="var(--td-success-color)" />
          示例
        </div>
        <span class="demo-subtitle">交互示例</span>
      </div>
    </template>
    <div class="demo-stage">
      <div class="demo-card">
        <t-avatar
          class="demo-mark"
          size="54px"
          shape="round"
          style="
            background: var(--td-brand-color);
            color: var(--td-text-color-anti);
            font-weight: 800;
          "
        >
          T
        </t-avatar>
        <t-typography-title class="demo-card-title" level="h3">Hello, TDesign</t-typography-title>
        <t-typography-paragraph class="demo-card-copy" theme="secondary">
          点击按钮，体验这个模板中的基础交互。
        </t-typography-paragraph>
        <t-space :size="12" align="center">
          <t-button theme="primary" size="large" shape="square" aria-label="减少" @click="decrease">
            −
          </t-button>
          <t-button variant="outline" size="large" disabled>{{ count }}</t-button>
          <t-button theme="primary" size="large" shape="square" aria-label="增加" @click="increase">
            +
          </t-button>
        </t-space>
        <div class="hint">编辑首页文件并保存，查看热更新效果</div>
      </div>
    </div>
  </t-card>
</template>
